{"name": "test_get2", "status": "skipped", "statusDetails": {"message": "XFAIL This test is expected to fail as the tes case cannot access fixture's return value\n\nFailed: Fixture \"setup_list\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/explanation/fixtures.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code.", "trace": "Fixture \"setup_list\" called directly. Fixtures are not meant to be called directly,\nbut are created automatically when test functions request them as parameters.\nSee https://docs.pytest.org/en/stable/explanation/fixtures.html for more information about fixtures, and\nhttps://docs.pytest.org/en/stable/deprecations.html#calling-fixtures-directly about how to update your code."}, "attachments": [{"name": "stdout", "source": "681112e3-1675-4c3d-9204-951451bed81d-attachment.txt", "type": "text/plain"}], "start": 1751799115813, "stop": 1751799115813, "uuid": "df499ce1-6135-4c6b-8e51-965df91a5f21", "historyId": "019f56072b4afbeb23dea756f6b67063", "testCaseId": "019f56072b4afbeb23dea756f6b67063", "fullName": "test_fixture02#test_get2", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='This test is expected to fail as the tes case cannot access fixture's return value')"}, {"name": "tag", "value": "@pytest.mark.usefixtures('setup_list')"}, {"name": "suite", "value": "test_fixture02"}, {"name": "host", "value": "Dell15"}, {"name": "thread", "value": "36220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_fixture02"}]}